-- SHOW ALL SCHEMAS IN THE DATABASE
SHOW DATABASES;
--- USING THE RIGHT DATABASE
USE DATABASE "GOOGLE_KEYWORDS_SEARCH_DATASET_DISCOVER_ALL_SEARCHES_ON_GOOGLE";


SHOW SCHEMAS;

USE SCHEMA "DATAFEEDS";


SHOW TABLES;

SHOW VIEWS;

